### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by NiniMine** [SkyCraft78/DiSky#11]
**Name:** `Multipage Embed`

**Potential New Syntaxes:**
* Effect: `make [a] [new] (1¦multipage|2¦pagination) embed from %object% [[[with] emoji %string% [for] previous[(-page| page)] [and] [[with] emoji %string% [for] next[(-page| page)]]`
* Event: `[on] (1¦multipage|2¦pagination) (page|site) switch:` (with event-values new-page, old-page, event-embed, event-member)

**In-dept description of the new features:**
```
Multipage embeds:
First you create your embeds normally and save them in a list. From this you can generate a multipage embed. To scroll through the pages you use 2 emojis (adjustable in the config or in the code). 

Pagination:
First you create your embeds normally and save them in a list, like multipage. But now instead of arrow left/right, numbers are displayed, to skip pages for example.
```

**Comment by SkyCraft78** [comment]
Hi, i'm planning to manage that from another way, using emote menu and embed page.
