### ISSUE TITLE
[REQUEST] Embed Template

### ISSUE THREAD

**Issue by NiniMine** [SkyCraft78/DiSky#12]
**Name:** `Embed template`

**Potential New Syntaxes:**
* Effect: `make new embed (from|with) template %string%`
* Effect: `make new embed and save [it] [as] temp[late] (named|with [the] name %string)%`

**In-dept description of the new features:**
```
You can create embed templates. So you don't have to create footer, author, timestamp etc always from scratch. But you can still change it in the actual embed.
```

**Comment by SkyCraft78** [comment]
It's a very good idea, i'll add it in 1.6.1, thanks ❤️

**Comment by vitusverden** [comment]
Effect would be 
`[disky] make [new] [discord] embed [((from|with) template %string%|and save [it] [as] template (named|with [the] name) %string%)]`
to be more intuitive and not be in conflict with the current `make embed` effect

**Comment by SkyCraft78** [comment]
Added, thanks for the idea ❤️
