### ISSUE TITLE
[REQUEST] Command registration-system

### ISSUE THREAD

**Issue by NiniMine** [SkyCraft78/DiSky#13]
**Name:** `Command registration-system`

**Potential New Syntaxes:**
* New command option: `category`, `command id` and another to disable registration (for team only commands) `register`
* New Type: `command`
* Expression: `[all] discord commads [from category %command%]`, `[the] usage of discord command %command%`, 
 `[the] description of discord command %command%`, `the category of discord command %command%`, ``permitted roles of discord command %command%

**In-dept description of the new features:**
```
A command registration system that automatically collects all commands you create (at discord command:). For example for a help command. You can get all commands, or only commands in a certain category. Of course you can do it yourself, but buildin is always better and more beginner friendly. 
```

**Comment by SkyCraft78** [comment]
All of these expressions aer pretty good. I'll add them for 1.7, thanks ❤️

**Comment by NiniMine** [comment]
Can you then also add a tracker of how often which command was used?
`uses of [discord] command %command%`

And one more addition to the above
`[all] discord commads [from category %command%] [ordered (ASC|DESC) by (uses|category|name|id)]`

**Comment by NiniMine** [comment]
yes

**Comment by SkyCraft78** [comment]
Added, thanks for the idea ❤️
