### ISSUE TITLE
[REQUEST] Updating documentation

### ISSUE THREAD

**Issue by vitusverden** [SkyCraft78/DiSky#14]
```
Skunity & skripthub docs are outdated as of 1.6. At some point, it would be nice to have them updated.
Low priority.
```

**Comment by SkyCraft78** [comment]
Are you sure about that ? I've updated them like an hour ago, refresh the page maybe ?

**Comment by SkyCraft78** [comment]
What do you mean ?

**Comment by vitusverden** [comment]
Right now they do not show up as updated, but I might just have to wait until the website shows them (it could be that the websites only updates their documentation at certain intervals, even when authors have updated theirs)
I will wait until it has been night in the United States (the servers will probably restart then) and check again.
