### ISSUE TITLE
[REQUEST] Some parity features from Vixio

### ISSUE THREAD

**Issue by NiniMine** [SkyCraft78/DiSky#16]
**Name:** `A few things that are missing at DiSky, but are available at vixio`

**Potential New Syntaxes:**
* Effect:
`(make|create) [a[n]] invite to %channel% [(with|as) %bot/string%]`
`shuffle [the] queue of %bot/string% [in %guild%]`
`pin %messages% [with %bot/string%]`
`create emote %string% with [the] name %string% [in %guild%] [with %bot/string%]`
`move %member% to %voicechannel% [with %bot/string%]`
`mute %members% [(with|using) %bot%]`
`disconnect %member% [from channel %channel%]`

* Conditions: 
`%member% (has|have) [the] role %role%`
`%attachments% (is|are) [a[n]] image[s]`
`%emotes% (is|are) animated`
`%members% (is|are) (deafened|muted)`
`attachment of %message% is set`

* Expression: 
`[the] (bans|ban list) of %guild%`
`the invite(s| link[s]) of %guild/channel%`
`%bot/string%'[s] guild[s]` / `[the] guild[s] of %bot/string%`

**In-dept description of the new features:**
```
yes.... what can i say? I hope I didn't write down anything that DiSky can already do.
In the file I have looked what is already there (generated with https://github.com/SkriptHub/SkriptHubDocsTool)
```
[DiSkyjson.txt](https://github.com/SkyCraft78/DiSky/files/6285013/DiSkyjson.txt)

**Comment by SkyCraft78** [comment]
Invites properties will come soon, but later. With it come the invite get on member join, invite creation with scope and go on.
The pin effect (and the way to get pinned messages) are already added in 1.6.
However, for almost everythings else, I could add them without problem, thanks for ideas!

**Comment by SkyCraft78** [comment]
Everythings is currently added, i can close that issue.
Thanks ❤️
