### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by OmarOmar93** [SkyCraft78/DiSky#17]
**Name:** `Adding Reactions To Embed and edit a embed with a new embed`

**Potential New Syntaxes:**
* Effect: `add reaction "*" to embed {_embed}

**Other syntaxes affected (if any):** `edit embed {_embed} with last created embed`

**In-dept description of the new features:**
```
I wanted to try to add a reaction to a embed message and i don't think there is any way to do it and also i wanted to edit a embed message with another last created embed
```

**Comment by SkyCraft78** [comment]
Hi, you can't add a resction to the **embed** but to the message.

**Comment by OmarOmar93** [comment]
okay but is there a feature that will add these both?

**Comment by SkyCraft78** [comment]
This won't be added snice it's just impossible.
You can't add a reaction to the **embed** itself, but to the **message** sent with the embed.
Use `... and store it in {_msg}` pattern at the end to get the sent message. You can now add the reaction to this variable.
