### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by NiniMine** [SkyCraft78/DiSky#18]
**Name:** `Adding playlist support`

**Potential New Syntaxes:**
* Effect: `add all tracks from playlist %string% to queue of %bot% in guild %guild%`

**In-dept description of the new features:**
```
You can either add the tracks directly to the queue, or just use the normal syntax so that the tracks are automatically added to the queue.
```

**Comment by SkyCraft78** [comment]
I won't add this one, cause it's the the DiSky's role.
You can easily do that through Skript list variable, adding track and playing them whenever you want.
