### ISSUE TITLE
[REQUEST] add %member% to remove event-emote effect

### ISSUE THREAD

**Issue by wallace4BR** [SkyCraft78/DiSky#22]
* Old Effect: `[disky] (remove|delete) %emote% added by %user% from %message% `
* New Effect: `[disky] (remove|delete) %emote% added by %member/user% from %message% `

**In-dept description of the new features:**
```
Since user is related to the member outside a guild i think this should be added
```

**Comment by SkyCraft78** [comment]
Added in 1.8
