### ISSUE TITLE
[REQUEST]  Retrieve message

### ISSUE THREAD

**Issue by wallace4BR** [SkyCraft78/DiSky#23]
**Description:** `Get a Message via it's ID from a Guild/TextChannel`

* Effect: `retrieve message [with id] %string% [(in|from) %channel/user%]`

**Comment by vitusverden** [comment]
Doesn't this already exist with the `message with id "ID"` syntax?

**Comment by DampfWaffel** [comment]
set {_id} to discord id of message ""
https://skripthub.net/docs/?id=4919

**Comment by vitusverden** [comment]
> `set {_id} to discord id of message ""`
> https://skripthub.net/docs/?id=4919

No, that would be the opposite of what OP wants. He wants message from id, not id from message.


But it does already exist: https://skripthub.net/docs/?id=4920

**Comment by SkyCraft78** [comment]
Hello !
You can already fo that with this expression: 
```applescript
[disky] message with [the] id %string% in [channel] %channel/textchannel%
```
It come from" entity from ID" on the docs:
https://skripthub.net/docs/?id=4920
I you're not able to make it proper work, please re-open the issue 😄
