### ISSUE TITLE
[REQUEST] Change Send Discord Message Effect

### ISSUE THREAD

**Issue by wallace4BR** [SkyCraft78/DiSky#24]
**Name:** `Change the send discord message effect`

* Old Effect: `[disky] send [message] %string/message/embed/messagebuilder% to [the] [(user|channel)] %user/member/textchannel/channel% [with [the] bot [(named|with name)] %string%] [and store it in %object%]`
* New Effect: `[disky] send [message] %string/message/embed/messagebuilder% to [the] [(user|channel)] %user/member/textchannel/channel% [with %string%] [and store it in %object%]`

**In-dept description of the new features:**

Make it `send "Test" to event-channel with "BotName"` instead of `send "test" to event-channel with bot named "BotName"`
it will make more easy to switch from vixio and it will be similar to Add Reaction effect (`[disky] (add|append) reaction %string% to [message] %message% with [bot] %string%`

**Comment by SkyCraft78** [comment]
Thanks, fixed in 1.8
