### ISSUE TITLE
[Issue] Reaction to stored embed

### ISSUE THREAD

**Issue by wallace4BR** [SkyCraft78/DiSky#25]
**Issue:** Reactions on embeds are not working

**Code:**
```
discord command /test:
	trigger:
		add reaction "😀" to event-message with "BotName" #works
		make new embed:
			set the description of embed to "Test"
		reply with last embed and store it in {_test}
		add reaction "😀" to {_test} with "BotName" #doesn't works
```

Return:
![image](https://user-images.githubusercontent.com/81590228/114317602-415e0f80-9adf-11eb-8541-1edbefd20608.png)

Expected:
![image](https://user-images.githubusercontent.com/81590228/114317624-533fb280-9adf-11eb-9a44-91714f0f8c2f.png)

No erros!

**Comment by SkyCraft78** [comment]
Thanks for the bug report.
It's fixed in 1.8 ❤️
