### ISSUE TITLE
[REQUEST] Missing %bot%

### ISSUE THREAD

**Issue by wallace4BR** [SkyCraft78/DiSky#27]
**Name:** Some syntaxes are missing %bot%

* **Syntax:** `[disky] [the] [member] %member% has [discord] permission %permission% [in [channel] %channel/textchannel%]`

**Other syntaxes affected (if any):** `[disky] [discord] [voice] channel of [the] [member] %member%`

**In-dept description of the new features:**
```
We need the %bot% aswell incase for checks
```

**Comment by SkyCraft78** [comment]
Fixed
