### ISSUE TITLE
[REQUEST] event-values on track

### ISSUE THREAD

**Issue by wallace4BR** [SkyCraft78/DiSky#28]
**Name:** Add more event-values to music events

* **Effect:** `[on] [discord] (audio|track) start` 

* **Example:**
```
on track start:
	send "%event-bot% is now playing in channel %discord name of event-channel%" to text channel with id ""
```

**Other syntaxes affected (if any):** `[on] [discord] (audio|track) end`

**In-dept description of the new features:**
```
They are helpful for music system %event-bot% and optionally %event-channel%
```

**Comment by SkyCraft78** [comment]
Added:
```
event-voicechannel
event-guild
event-bot
event-track
```
Thanks for suggestion!
