### ISSUE TITLE
[REQUEST] Syntaxes for voice

### ISSUE THREAD

**Issue by wallace4BR** [SkyCraft78/DiSky#29]
* Effects: `Join voice channel of %member%`
`make bot (leave|disconnect from) (voice|vc) [in %guild%]`
`Mute %member|bot%`
`Deafen %member|bot%`
`Move member to %voice channel%`
`%bot% is playing [in %guild%]`

* Events: `On Voice Channel Join` 
 `on Voice Channel Leave`
`on member switch voice channel`

**Comment by SkyCraft78** [comment]
Added thanks
