### ISSUE TITLE
[REQUEST] Effect - Pause track

### ISSUE THREAD

**Issue by wallace4BR** [SkyCraft78/DiSky#3]
**Name:** `Pause track effect for music system`

* Effect: `pause [the] (track|song) %bot/string% is playing [in %guild%]`

**Description of the new feature:** Make this expression for pausing the current track bot is playing in a guild, if it is already paused nothing happens

**Comment by VintagixDev** [comment]
already planned

**Comment by SkyCraft78** [comment]
Added in 9854ac4
