### ISSUE TITLE
[REQUEST] react to run event-values

### ISSUE THREAD

**Issue by NiniMine** [SkyCraft78/DiSky#31]
**Name:** `<feature name>`

**Event-values:** `event-member`, `event-textchannel`, `event-message`, `event-guild`

**In-dept description of the new features:**
```
Can you please provide some event values that can be used in the code section `react to run`?
```

**Comment by SkyCraft78** [comment]
Hello!
It doesn't really depend of me, i'm trying all my possible to manage these but Skript API doesn't provide any easy way :(
