### ISSUE TITLE
[REQUEST] Standard prefix

### ISSUE THREAD

**Issue by NiniMine** [SkyCraft78/DiSky#32]
**Name:** `Standard prefix`

**Effect:** `set [the] standart prefix of [[the] bot] %bot% to %object%`
- Object, so that you can use a list.
**In-dept description of the new features:**
```
A standard prefix that you can set when loading the bot, which then applies to all commands.
```

**Comment by SkyCraft78** [comment]
Hello!
It's a good idea thanks, i'll add it for 1.8.1!
