### ISSUE TITLE
[BUG] Queue is empty when a track stops

### ISSUE THREAD

**Issue by ReportCardsMC** [SkyCraft78/DiSky#33]
**BUG**
When you let a song run it's course (I used a 5 sec vid to re-test multiple times) it clears the queue kind of, when you play a new song it brings the queue back. But with this it doesn't go through the queue as normal.

**REPRODUCE**
- Play 2 songs, make sure second is queued.
- Let first song play through (Don't skip)
- Check queue and/or now playing

**Comment by ReportCardsMC** [comment]
Versions:
Server - Paper git-Paper-592
Skript - 2.5.3
DiSky - 1.8

**Comment by SkyCraft78** [comment]
Hello!
As said in the documentation, the stop effect will disconnect the bot AND **clear the queue**.
It's not a bug, it was planned ^^

**Comment by ReportCardsMC** [comment]
Not what I meant in the issue, I meant the bot doesn't automatically continue through the queue as a song ends.

**Comment by NiniMine** [comment]
I have also asked this before and received an answer: That is not DiSky's task.

**Comment by SkyCraft78** [comment]
It's not what DiSky (or vixio) do.
Use an event, is just two line:
```applescript
on track end:
	skip current track of event-guild
```
It will work as a "real queue" as you define it.
