### ISSUE TITLE
[REQUEST] More event-values 

### ISSUE THREAD

**Issue by wallace4BR** [SkyCraft78/DiSky#37]
* Event: `[on] [discord] [member] [voice] channel move`

**Event-Values:** `event-oldchannel` - `event-newchannel`

**Comment by SkyCraft78** [comment]
Hello!
Unfortunaly, Skript doesn't provide a good way to manage as want the event values.
I'm currently making my own system of updating value (when anythings is updated, an "old" and a "new" value), which will replace the current event value ones.
