### ISSUE TITLE
[REQUEST] Missing %bot% v2

### ISSUE THREAD

**Issue by wallace4BR** [SkyCraft78/DiSky#40]
**Potential old syntaxes:** 
1° `[disky] [discord] [voice] channel of [the] [member] %member%`
2° `[disky] [the] bot is [currently] playing in [the] [guild] %guild%` - `[disky] [the] bot (is not|isn't) [currently] playing in [the] [guild] %guild%`
3º `[disky] [the] [discord] mention [tag] of [the] [discord] [entity] %role/emote/user/member/channel/textchannel%`
4º `[disky] (add|append) %emotes% to [message] %message% with [bot] %string%`
5 `[disky] (remove|delete) %emotes% added by %user/member% from %message%`
6° `[disky] (make|send) [bot] typing in [the] [channel] %channel/textchannel%`

New: 
1° `[disky] [discord] [voice] channel of [the] %bot|member%`
2° `[disky] [the] %bot% is [currently] playing in [the] [guild] %guild%` - `[disky] [the] %bot% (is not|isn't) [currently] playing in [the] [guild] %guild%`
3° `[disky] [the] [discord] mention [tag] of [the] [discord] [entity] %role/emote/user/member/bot/channel/textchannel%`
4° `[disky] (add|append) %emotes% to [message] %message% with [bot] %bot%`
5 `[disky] (remove|delete) %emotes% added by %bot/user/member% from %message%`
6° `[disky] (make|send) %bot% typing in [the] [channel] %channel/textchannel%`

**Events:** 7° `On reaction add` - `On reaction remove`

New event-value: `event-bot`

**In-depth description of the new features:**
```
1° Checking if the bot is in a voice channel.
2° Checking if certain bot is playing.
3° using mention tag of bot.
4° using event-bot to commands
5° removing reactions from the bot
6° Specify the bot on typing 
7° Checking when the bot add/remove reactions in a message
```

**Comment by SkyCraft78** [comment]
I fully reworked the bot system since the 5cfbc89 commits.
Every syntaxes or event are using a `bot` type, which can be easily getted with the **new** `[the] bot [(named|with name)] %string%`
I think it's a much more better way, and the code beside is pretty much optimized.
