### ISSUE TITLE
[REQUEST] Syntaxes changes

### ISSUE THREAD

**Issue by wallace4BR** [SkyCraft78/DiSky#42]
**Potential old syntaxes:** 
1° `[disky] new [discord] message builder`
2° `[disky] (add|append) %emotes% to [message] %message% with [bot] %bot%`
3° `[disky] append %string/embed% to [message] builder %messagebuilder%`

**New syntaxes:**
1° `[disky] a new [discord] message builder`
2° `[disky] (add|append) %emotes% to [reactions of] %message% with [bot] %string%`
3° `[disky] append %string/embed% to [message] [builder] %messagebuilder%`

**In-depth description of the new features:**
```
1° A new message builder instead of new message builder. (better and right spreading when migrating from vixio)
2° Make a new optional "reactions of" (Better when migrating from vixio)
3° Make optional "messages builder" (Better when migrating from vixio)
```

**Comment by SkyCraft78** [comment]
Done, thanks ❤️
