### ISSUE TITLE
[BUG] There is a strange code when I give a variable with a format string The API from Ultimatechat uses the skript-reflect

### ISSUE THREAD

**Issue by LowScarlet** [SkyCraft78/DiSky#43]
**Name:** `Disky 1.1`
**Versions:** `1.16.5 paper  `

Code
````
import:
	br.net.fabiozumbi12.UltimateChat.Bukkit.API.SendChannelMessageEvent
on SendChannelMessageEvent:
	cancel event
	set {_list::player} to event.getSender()
	set {_list::message} to event.getMessage()

        send {_list::message}  to channel with id discordGetlivechatId() with discordGetname()
        broadcast {_list::message}
````
The output from the minecraft chat looks fine, but when I saw the output from the Discord channel there was a strange code after the chat
![image](https://user-images.githubusercontent.com/64282946/116095827-f5ac8800-a6d2-11eb-9211-690ed39a7e9f.png)
![image](https://user-images.githubusercontent.com/64282946/116095923-0957ee80-a6d3-11eb-9ce3-0e7e8645f85b.png)

**Comment by SkyCraft78** [comment]
Hi, first of all try updating DiSky to 1.10

**Comment by LowScarlet** [comment]
> Hi, first of all try updating DiSky to 1.10

but I just downloaded the latest version from this link https://github.com/SkyCraft78/DiSky/releases/tag/1.10
![image](https://user-images.githubusercontent.com/64282946/116096732-b9c5f280-a6d3-11eb-8581-89f37c314ae7.png)

**Comment by SkyCraft78** [comment]
Oh okay, sorry, you've writed 1.1 so i through it was the first version 😂

**Comment by LowScarlet** [comment]
> Oh okay, sorry, you've writed 1.1 so i through it was the first version 😂
> Ooops, look likes i've bad editing the plugin file of DiSky too :(

So you mean you uploaded the latest version wrong?

**Comment by SkyCraft78** [comment]
What, **in the game**, the `event.getMessage()` return ?

**Comment by SkyCraft78** [comment]
> Oh okay, sorry, you've writed 1.1 so i through it was the first version 😂
> Ooops, look likes i've bad editing the plugin file of DiSky too :(

Nope don't worry, i just forgotten to change the version in the showing file x)

**Comment by LowScarlet** [comment]
> What, **in the game**, the `event.getMessage()` return ?

Chats from players that have been modified by the ultimatechat plugin

**Comment by LowScarlet** [comment]
![image](https://user-images.githubusercontent.com/64282946/116097547-715b0480-a6d4-11eb-8112-4329535b1a01.png)
look like this

**Comment by SkyCraft78** [comment]
So you don't have the weird `<chat=>` things?

**Comment by wallace4BR** [comment]
> **Name:** `Disky 1.1`
> **Versions:** `1.16.5 paper `
> 
> Code
> 
> ```
> import:
> 	br.net.fabiozumbi12.UltimateChat.Bukkit.API.SendChannelMessageEvent
> on SendChannelMessageEvent:
> 	cancel event
> 	set {_list::player} to event.getSender()
> 	set {_list::message} to event.getMessage()
> 
>         send {_list::message}  to channel with id discordGetlivechatId() with discordGetname()
>         broadcast {_list::message}
> ```
> 
> The output from the minecraft chat looks fine, but when I saw the output from the Discord channel there was a strange code after the chat
> ![image](https://user-images.githubusercontent.com/64282946/116095827-f5ac8800-a6d2-11eb-9211-690ed39a7e9f.png)
> ![image](https://user-images.githubusercontent.com/64282946/116095923-0957ee80-a6d3-11eb-9ce3-0e7e8645f85b.png)

I think it's because you're not using it as a string
Try 
`send "%{_list::message}%"  to channel with id discordGetlivechatId() with discordGetname()`

Or
`set {_list::message} to "%event.getMessage()%"`

**Comment by LowScarlet** [comment]
> > **Name:** `Disky 1.1`
> > **Versions:** `1.16.5 paper `
> > Code
> > ```
> > import:
> > 	br.net.fabiozumbi12.UltimateChat.Bukkit.API.SendChannelMessageEvent
> > on SendChannelMessageEvent:
> > 	cancel event
> > 	set {_list::player} to event.getSender()
> > 	set {_list::message} to event.getMessage()
> > 
> >         send {_list::message}  to channel with id discordGetlivechatId() with discordGetname()
> >         broadcast {_list::message}
> > ```
> > 
> > 
> > The output from the minecraft chat looks fine, but when I saw the output from the Discord channel there was a strange code after the chat
> > ![image](https://user-images.githubusercontent.com/64282946/116095827-f5ac8800-a6d2-11eb-9211-690ed39a7e9f.png)
> > ![image](https://user-images.githubusercontent.com/64282946/116095923-0957ee80-a6d3-11eb-9ce3-0e7e8645f85b.png)
> 
> I think it's because you're not using it as a string
> Try
> `send "%{_list::message}%" to channel with id discordGetlivechatId() with discordGetname()`
> 
> Or
> `set {_list::message} to "%event.getMessage()%"`

I have tried it before but I will try again

**Comment by SkyCraft78** [comment]
Nope it won't work

**Comment by LowScarlet** [comment]
> Nope it won't work

yes it doesn't work

**Comment by SkyCraft78** [comment]
Come to discord if possible ^^
