### ISSUE TITLE
[BUG] On Voice Channel Leave Event

### ISSUE THREAD

**Issue by wallace4BR** [SkyCraft78/DiSky#44]
**Versions:** `1.10`

**Syntaxes affected:** On Voice Channel Leave

**In-depth description of the bug:**
Code:
```
on voice channel join:
	broadcast "%event-voicechannel%"
	broadcast "%event-channel%"
	broadcast "%discord id of event-channel%"
	broadcast "%discord name of event-channel%"
```
Returns:
![image](https://user-images.githubusercontent.com/81590228/116799168-20c91a00-aacd-11eb-83b7-fe8b432a210a.png)

Code:
```
on voice channel leave:
    broadcast "%event-voicechannel%"
    broadcast "%event-channel%"
    broadcast "%discord id of event-channel%"
    broadcast "%discord name of event-channel%"`
```

Returns:
![image](https://user-images.githubusercontent.com/81590228/116799180-3a6a6180-aacd-11eb-9cbb-cd98a0f62321.png)

**Comment by SkyCraft78** [comment]
Please describe a little more your problem.
The code is same but output are different as what i see

**Comment by SkyCraft78** [comment]
Hum it's very wierd, it work fine from my side.
Have you've been enabled every intents ?

**Comment by wallace4BR** [comment]
Closing it as it has been fixed at discord
