### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by Olyno** [SkyCraft78/DiSky#45]
Hi,

As you have retrieved [a code that you did not create](https://github.com/SkyCraft78/DiSky/blob/master/src/main/java/info/itsthesky/DiSky/tools/MultiplyPropertyExpression.java#L1), and that it belongs to [Skron](https://github.com/Olyno/Skron/blob/master/src/main/java/com/olyno/skron/util/MultiplePropertyExpression.java)'s project which has no license, meaning it is automatically under copyright, and used in the template [myaddon](https://github.com/Olyno/myaddon/blob/master/app/src/main/java/com/author/myaddon/utils/skript/MultiplePropertyExpression.java). Because of this, I would ask you to put a copyright notice on this file.
Unauthorized code theft is of course condemnable by the law. I will give you my permission once the copyright is added to the file.

I would ask you to add the following notice at the top of the corresponding file:

```
<one line to give the program's name and a brief idea of what it does.>
Copyright (C) <year>  <name of author>
```

By filling in the different fields of course. I would ask you too to put back the comments you deleted.

Sincerely, Olyno

**Comment by SkyCraft78** [comment]
Hey!
I don't know how I managed, I had used the code of skDynmap, and as I just checked, the copyright is well on this code.
I'm really sorry, the copyright will be added in the next wave of commits.
Thanks for the report,
Regards,
Sky.
