### ISSUE TITLE
[REQUEST] Interactivechat Support

### ISSUE THREAD

**Issue by LowScarlet** [SkyCraft78/DiSky#49]
**Name:** `Interactivechat Support`

**In-depth description of the new features:**

Support for [interactivechat](https://www.spigotmc.org/resources/interactivechat-show-items-inventory-in-chat-custom-chat-keywords-bungee-velocity-support.75870/?__cf_chl_jschl_tk__=09decc42d3190219054935f9666813233d560d1f-1620468994-0-AU3DLpPGyBgauf-kzjoMpEaw2coQI8EXesaAgZcZR59ksCqNHvSRgOyuPcqYOxmVtHE1OzOW2b9bMWAryeyWZJh821aZY8PYFBQcxFNdnfMiTp8DhIBQeLDLC3m2Xpm5F40_HDQAlHU-7s1avhoGRsjfczcbJSNy0TqAw581JuCqvqv3Oo0rZhsF1YuCWKar6LYgRDYGiauE2CmTBI7iQlzx6ASUMcATLYb6YBxoCyQ2CbVmdTa9bQqYU0u0dTrsh-0bF19t8WXbeAfuHPmULgE4_bvkLdVXhicKnbIOa1l8v7e0RVrfBwH3mDOGoekNS576bBX-KuOydS2X60wmB3O8MIdc7Q6zGf1zQ5ybsap835l33ghgphbFHejJX8zpfWOdjmWWfOWp0XiIoJhUF106OHghE6XWvyz8ZoNaIPyLIeIVc6YvuJx0zVg7otVsySHtjBTG6u1qSrE4opDoUrCwcwU3-cCkZf83MruBIcDg_PyLspPZq0qm-gUJErHFbJkdp_cFXtL6elI93pT3dFcHc08Yul9T3cAXt6DYq0MW) plugins such as [Interactivechat discordsrv addon](https://www.spigotmc.org/resources/interactivechat-discordsrv-addon-show-items-and-invs-on-discord-preview-discord-images-in-game.83917/), Maybe it will make these plugins even more interesting?
# Screenshot feature
![image](https://user-images.githubusercontent.com/64282946/117535825-c62a4380-b021-11eb-8e36-adf5352b114e.png)
![image](https://user-images.githubusercontent.com/64282946/117535834-d5a98c80-b021-11eb-8bce-4377fb2f3d82.png)
![image](https://user-images.githubusercontent.com/64282946/117535846-dfcb8b00-b021-11eb-99d0-521fbec64395.png)
![image](https://user-images.githubusercontent.com/64282946/117535855-e78b2f80-b021-11eb-94a9-ea1dc3980596.png)

**Comment by SkyCraft78** [comment]
Hum i don't understand what DiSky should do here ?
You can already set image in an embed tooo idk

**Comment by LowScarlet** [comment]
> Hum i don't understand what DiSky should do here ?
> You can already set image in an embed tooo idk

That's not it .. you take a look at the addon plugins

**Comment by LowScarlet** [comment]
it's something more interesting than that ...

**Comment by SkyCraft78** [comment]
Then explain it better, i don't udnerstand what you mean

**Comment by LowScarlet** [comment]
Ok alright, if I'm going to ask, how do I embed it with an inventory player image like this
![image](https://user-images.githubusercontent.com/64282946/117536508-8a917880-b025-11eb-88c1-edfba337fa0c.png)

**Comment by SkyCraft78** [comment]
You want DiSky do that ?

**Comment by LowScarlet** [comment]
That's a suggestion

**Comment by SkyCraft78** [comment]
Not the DiSky role
See over SkImage to create image yourself, then upload them using DiSky

**Comment by LowScarlet** [comment]
lol

**Comment by SkyCraft78** [comment]
What "lol" ?

**Comment by LowScarlet** [comment]
suck , im out You don't even see what the sample plugins I provide do

**Comment by SkyCraft78** [comment]
I saw, embeding image like inventory or tooltips
However as i said, DiSky is here to link Discord with Skript
It's not a replacement to any sort of other plugins.
Using DiSky & SkImage (even skript-json if you wanna get custom textures like screens showed) you can easily do it yourself.

**Comment by LowScarlet** [comment]
> I saw, embeding image like inventory or tooltips
> However as i said, DiSky is here to link Discord with Skript
> It's not a replacement to any sort of other plugins.
> Using DiSky & SkImage (even skript-json if you wanna get custom textures like screens showed) you can easily do it yourself.

Do you think this inventory screenshot is from a photo uploaded by the player or from a link?

**Comment by LowScarlet** [comment]
If yes it's not, lmao that's why I said first look at the link that I provide for you

**Comment by SkyCraft78** [comment]
None of them.
I'm pretty sure the plugin take every icon of each item, and add the amount in the bottom rght corner.
Then, take an empty inventory image and paste every item at their desired slots.
They're using [MCHead](https://mc-heads.net/) to paste the skin of the player & his armor.

**Comment by SkyCraft78** [comment]
I'll not change what i said, this won't be added to DiSky since it's not the DiSky role.
