### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by AggerTV** [SkyCraft78/DiSky#5]
Hello, since I can't post on the discord, I will post here. I just started playing with this addon, and I have a question. This is my code, how will I remove the gray second message? 
picture:
https://gyazo.com/707af650782a59bd5f6d7cb22ccd3335

code:
https://gist.github.com/AggerTV/912fea1df315649573253fbe0cea717e

**Comment by SkyCraft78** [comment]
Hi!
Could you try to format your code please ?
I can't see it with multiple line :(
Use three ` around your code for that ^^

**Comment by AggerTV** [comment]
`discord command test [<text>]:
	prefixes: .
	executable in: guild
	trigger:
		make embed:
			set title of embed to "Titel?"
			add "Linje 1" to {_l::*}
			add "Linje 2" to {_l::*}
			add "Linje 3" to {_l::*}
			add "Linje 4" to {_l::*}
			add "Linje 5" to {_l::*}
			set description of embed to join {_l::*} with nl
			set thumbnail of embed to avatar of arg-1
			set footer of embed to "Asked by %discord name of event-member%"
			set description of embed to join {_l::*} with nl
			set color of embed to color of event-member
			set timestamp of embed to now
		reply with last embed`

**Comment by SkyCraft78** [comment]
Nah, you're using only one `
the final result will be like ```Hello World```

**Comment by AggerTV** [comment]
``discord command test [<text>]:
	prefixes: .
	executable in: guild
	trigger:
		make embed:
			set title of embed to "Titel?"
			add "Linje 1" to {_l::*}
			add "Linje 2" to {_l::*}
			add "Linje 3" to {_l::*}
			add "Linje 4" to {_l::*}
			add "Linje 5" to {_l::*}
			set description of embed to join {_l::*} with nl
			set thumbnail of embed to avatar of arg-1
			set footer of embed to "Asked by %discord name of event-member%"
			set description of embed to join {_l::*} with nl
			set color of embed to color of event-member
			set timestamp of embed to now
		reply with last embed``
Like this?

**Comment by AggerTV** [comment]
I don't understand why it's not working, I know how to format discord code :T

**Comment by AggerTV** [comment]
``discord command test [<text>]:
    prefixes: .
    executable in: guild
    trigger:
        make embed:
            set title of embed to "Titel?"
            add "Linje 1" to {_l::*}
            add "Linje 2" to {_l::*}
            add "Linje 3" to {_l::*}
            add "Linje 4" to {_l::*}
            add "Linje 5" to {_l::*}
            set description of embed to join {_l::*} with nl
            set thumbnail of embed to avatar of arg-1
            set footer of embed to "Asked by %discord name of event-member%"
            set description of embed to join {_l::*} with nl
            set color of embed to color of event-member
            set timestamp of embed to now
        reply with last embed``

**Comment by SkyCraft78** [comment]
Nope, but anyway i'll try to format it myself XD
So you're code is 
```
discord command test [<text>]: 
	prefixes: . 
	executable in: guild 
	trigger: 
		make embed: 
			set title of embed to "Titel?" 
			add "Linje 1" to {_l::*} 
			add "Linje 2" to {_l::*} 
			add "Linje 3" to {_l::*} 
			add "Linje 4" to {_l::*} 
			add "Linje 5" to {_l::*} 
			set description of embed to join {_l::*} with nl 
			set thumbnail of embed to avatar of arg-1 
			set footer of embed to "Asked by %discord name of event-member%" 
			set description of embed to join {_l::*} with nl 
			set color of embed to color of event-member 
			set timestamp of embed to now 
		reply with last embed
```
right ?

**Comment by AggerTV** [comment]
yes,
`````discord command test [<text>]:
    prefixes: .
    executable in: guild
    trigger:
        make embed:
            set title of embed to "Titel?"
            add "Linje 1" to {_l::*}
            add "Linje 2" to {_l::*}
            add "Linje 3" to {_l::*}
            add "Linje 4" to {_l::*}
            add "Linje 5" to {_l::*}
            set description of embed to join {_l::*} with nl
            set thumbnail of embed to avatar of arg-1
            set footer of embed to "Asked by %discord name of event-member%"
            set description of embed to join {_l::*} with nl
            set color of embed to color of event-member
            set timestamp of embed to now
        reply with last embed```

**Comment by SkyCraft78** [comment]
You're currently set the description of embed two time

**Comment by AggerTV** [comment]
okay, could you send the code that only shows the 1 box?

**Comment by SkyCraft78** [comment]
Simply remove on of your set description line, it should work ^^

**Comment by AggerTV** [comment]
I removed 1, but it still sends 2 messages
```discord command test [<text>]:
	prefixes: .
	executable in: guild
	trigger:
		make embed:
			set title of embed to "Titel?"
			add "Linje 1" to {_l::*}
			add "Linje 2" to {_l::*}
			add "Linje 3" to {_l::*}
			add "Linje 4" to {_l::*}
			add "Linje 5" to {_l::*}
			set thumbnail of embed to avatar of event-member
			set footer of embed to "Asked by %discord name of event-member%"
			set description of embed to join {_l::*} with nl
			set color of embed to color of event-member
			set timestamp of embed to now
		reply with last embed```

**Comment by AggerTV** [comment]
I really don't know why, this also is send 2 times
https://gyazo.com/9025df66c2a2a4ef8f0fc12d31e3254f

```discord command test [<text>]:
	prefixes: .
	executable in: guild
	trigger:
		make new embed:

			#To set the embed's title
			set title of embed to "Hey ! I'm a Title !"

			#To set the description of the embed
			set description of embed to "I'm the description of this amazing embed!"

			#To add field to your embed
			add field named "I am the name of the field" with value "I am the field's value." to embed

			#To set the image of your embed
			set image of embed to "http://image.noelshack.com/fichiers/2021/11/4/1616077049-4515f7a7575f87fa88c1e95c157e3f78.png"

			#To set the thumbnail of your embed
			set thumbnail of embed to "http://image.noelshack.com/fichiers/2021/11/4/1616077049-4515f7a7575f87fa88c1e95c157e3f78.png"

			#To set the footer of your embed
			set footer of embed to "I'm a footer"
		
			#To set the timestamp of your embed
			set timestamp of embed to now
		  
			#To set the color of your embed
			set color of embed to yellow
       
		#Now that you created your embed, just send it.
		reply with the last created embed```

**Comment by SkyCraft78** [comment]
Hey!
Are you sure you only have one instance of the bot ?
Try restarting your whole server and say me if the bugs is always here.

**Comment by AggerTV** [comment]
Restart my server? My discord or minecraft server? If my minecraft server, then I have already done that

**Comment by SkyCraft78** [comment]
Yes your Minecraft Server.
Else, could you send me your whole code (so the loading effect too) (**don't forget to remove the token!**) please ?

**Comment by AggerTV** [comment]
Yes sure!
```on load:
	login to "" with name "AgBot"
	change status of bot "AgBot" to do not disturb
	mark the bot named "AgBot" watching "Den helt nye AgPrison Discord bot!"
	
	
	
discord command whois [<member=%event-member%>]:
	prefixes: !
	executable in: guild
	trigger:
		make embed:
			set title of embed to "Who is %discord name of arg-1% ?"
			add "`•` Username: %discord name of arg 1%" to {_l::*}
			add "`•` Nick: %discord nickname of arg 1%" to {_l::*}
			add "`•` Tag: %tag of arg 1%" to {_l::*}
			add "`•` Mention: %mention tag of arg 1%" to {_l::*}
			add "`•` Mutual Guild: %size of mutual guild of arg 1%" to {_l::*}
			set description of embed to join {_l::*} with nl
			set thumbnail of embed to avatar of arg-1
			set footer of embed to "Asked by %discord name of event-member%"
			set description of embed to join {_l::*} with nl
			set color of embed to color of arg-1
			set timestamp of embed to now
		reply with last embed
		
discord command test [<text>]:
	prefixes: .
	executable in: guild
	trigger:
		make new embed:

			#To set the embed's title
			set title of embed to "Hey ! I'm a Title !"

			#To set the description of the embed
			set description of embed to "I'm the description of this amazing embed!"

			#To add field to your embed
			add field named "I am the name of the field" with value "I am the field's value." to embed

			#To set the image of your embed
			set image of embed to "http://image.noelshack.com/fichiers/2021/11/4/1616077049-4515f7a7575f87fa88c1e95c157e3f78.png"

			#To set the thumbnail of your embed
			set thumbnail of embed to "http://image.noelshack.com/fichiers/2021/11/4/1616077049-4515f7a7575f87fa88c1e95c157e3f78.png"

			#To set the footer of your embed
			set footer of embed to "I'm a footer"
		
			#To set the timestamp of your embed
			set timestamp of embed to now
		  
			#To set the color of your embed
			set color of embed to yellow
       
		#Now that you created your embed, just send it.
		reply with the last created embed
		```

**Comment by SkyCraft78** [comment]
Hum it's very weird, on which version of Minecraft, Skript and DiSky you're on ?

**Comment by AggerTV** [comment]
```[Server] INFO Server Version: git-Tuinity-"1b0d783" (MC: 1.16.5)
[Server] INFO Skript Version: 2.5.3
[Server] INFO - DiSky v1.5.1 (https://disky.itsthesky.info/)```

**Comment by SkyCraft78** [comment]
Could you try the latest beta version please ?

**Comment by AggerTV** [comment]
it's fixed now.
