### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by LowScarlet** [SkyCraft78/DiSky#53]
**Name:** `react to message`
**Versions:** `1.11`

Code: https://pastebin.com/Fh5SaCYj

**In-depth description of the bug:**

There is an error in the console when doing the code (the code link is above), I have checked and it is most likely on line 21 and 23 when triggering the function everything is going well but there are 2 things that I think are strange, namely an error in the console , then the TPS server immediately dropped to 18 tps which means very heavy

this error https://pastebin.com/5eAMJRke

**Comment by SkyCraft78** [comment]
It's fixed in 1.12, thanks for the report 😄
