### ISSUE TITLE
DiSKy doesn't load (Mohist 1.12.2)

### ISSUE THREAD

**Issue by PIZZAAXX** [SkyCraft78/DiSky#54]
i'm running Mohist v209 for MC 1.12.2, with Skript v2.5.3, and it gives this error when starting the server:

https://pastebin.com/Errw6kmE

**Comment by carlodrift** [comment]
Skript doesn't work well on Mohist

**Comment by SkyCraft78** [comment]
Hi, look likes you have a corrupted version of DiSky. 
Since you are on the discord, could you try the 1.12 ? It's pinned in the #support channel. 
Thanks 😄

**Comment by SkyCraft78** [comment]
So answer, I'm closing this one.
