### ISSUE TITLE
[BUG] Handler Conflic

### ISSUE THREAD

**Issue by LowScarlet** [SkyCraft78/DiSky#58]
**Name:** `last embed`
**Versions:** `1.13/1,14`

**Syntaxes affected:**
* Expression: `last embed`

**In-depth description of the bug:**
This expression will conflict with different code if triggered at the same time eg `on load` and `on script start`

**Comment by SkyCraft78** [comment]
As said on the Discord, it doesn't come from me, it comes from how Skript is executed. I however don't recommend at all executing anything thread-related in the `on skript load` event, use the `on load` ones instead.
The first one assumes Skript is loaded but **maybe not** the addons and everything which is not in Skript by default, here's, why.
