### ISSUE TITLE
[REQUEST] is message from id exist

### ISSUE THREAD

**Issue by LowScarlet** [SkyCraft78/DiSky#59]
**Name:** `Checks whether the message from the id is on a channel`

**Potential new syntaxes:**
* Condition: `message from id %string% is exist`

**Other syntaxes affected (if any):** `if message from id {_idmessage} is exist:`

**In-depth description of the new features:**
Checks whether the message from the id is on a channel

**Comment by SkyCraft78** [comment]
Can use either `message with id` expression or `retrieve the message with id` effect, and check if the returned value is set or not.
So can be done without DiSky and also be more efficient.
