### ISSUE TITLE
[BUG] Handler issues (2)

### ISSUE THREAD

**Issue by LowScarlet** [SkyCraft78/DiSky#66]
**Name:** `last embed`
**Versions:** `2.1 (1.17 paper)`

**Syntaxes affected:**
* Expression: `last embed`

**In-depth description of the bug:**
Previously I had made a report for this problem in version 1.13 (perhaps.. I forgot), before I used version 1.12 because this version which I think is stable and the bugs can still be tricked, But for version 1.13 I got a serious problem, namely the handler problem for the expression "last embed" which will conflict with other codes that are even different files, for example the first "last embed" is in the discord-2.sk file, then I make another "last embed" in the discord-3.sk file and then i use "last embed" in "on load" event then it will conflict with other last embed, this problem doesn't exist in version 1.12 only exists in version above

**Comment by LowScarlet** [comment]
I hope you don't close this issue again without a resolution or even a correct answer srius, I've made this issue 2x or maybe 3x in the last 2 months(? maybe)

**Comment by SkyCraft78** [comment]
Hi, 
I will say exact the same as I said in the last issue. 
This is **not** caused by DiSky, but Skript. Using `on load` or `on Skript load` will change the default Timing of how Skript works, and could be executed before or after the wanted time. 
So for the third time as you've said lmao, I cannot fix that, use embed template instead. 
Thanks

**Comment by LowScarlet** [comment]
Well that seems good, it made my decision to return to vixio even bigger
thank you

**Comment by SkyCraft78** [comment]
If you wanna keep a not updated version with bug and less features, it's your choice 😄
No problem for help and have a nice day 🙂
