### ISSUE TITLE
[BUG] Embed color does not support variables (locals and static variables)

### ISSUE THREAD

**Issue by Rephrasing** [SkyCraft78/DiSky#68]
**Name:** `Embed`
**Versions:** `DiSky 2.1 | Skript 2.5.3`

**Syntaxes affected:**
* Effect: `set color of embed to %color%`

**In-depth description of the bug:**
```
        make embed:
            set title of embed to "a"
            set {_r} to 5
            set {_g} to 2
            set {_b} to 1
            set color of embed to color from rgb {_r}, {_g}, {_b}
        reply with last made embed
```
Tried setting the 3 local-variables to `random <integer|number> between 0 and 255`
also tried setting the numbers to a static variable `ex. {r}, {g}, {b}`
Gives no errors in console

Always returns `gray` color

**Comment by TrasonCo** [comment]
THis is not really true cause vxtoxx_ do use variables there

**Comment by SkyCraft78** [comment]
Hi, do you have SkImage installed by any way?

**Comment by Rephrasing** [comment]
> Hi, do you have SkImage installed by any way?

Yes I do have SkImage

**Comment by SkyCraft78** [comment]
It's fully related to SkImage, moved there, thanks for the report 😄
