### ISSUE TITLE
[BUG] User with ID not working on some accounts.

### ISSUE THREAD

**Issue by Baezor1** [SkyCraft78/DiSky#69]
**Name:** `User with id`
**Versions:** `2.1`

**Syntaxes affected:**
* Expression: `user with id %id%`

**In-depth description of the bug:**

Some accounts (such as a new one I made) arent working when you try the user with id expression.
![Screen Shot 2021-07-24 at 8 42 18 PM](https://user-images.githubusercontent.com/64096464/126884961-5cab47d4-ec81-45e5-9217-856874a0575d.png)
<img width="468" alt="Screen Shot 2021-07-24 at 8 42 30 PM" src="https://user-images.githubusercontent.com/64096464/126884963-446e8f06-1306-4014-8781-dcde947d89ad.png">
This is the code i'm using for this.
![Screen Shot 2021-07-24 at 8 42 59 PM](https://user-images.githubusercontent.com/64096464/126884970-9beda517-94ca-4a2b-b8c8-e0ef23cf019e.png)

the variable `{_id}` is this line here `set {_id} to id of event-user`

**Comment by Baezor1** [comment]
Here is a better way to see this issue. Same command.

command:
```
discord command test:
	prefixes: ?
	bots: {@bot}
	trigger:
		set {_id} to id of event-user
		send "%user with id {_id}%" to event-user with bot "{@bot}" 
```
The output of this command is below.

Main Account:
<img width="390" alt="Screen Shot 2021-07-24 at 8 47 38 PM" src="https://user-images.githubusercontent.com/64096464/126885029-836bdbea-53b9-498e-bb69-fcdeae17d715.png">

Alt Account:
![Screen Shot 2021-07-24 at 8 48 00 PM](https://user-images.githubusercontent.com/64096464/126885040-e993dbda-8c01-4027-8578-e61e8f19ca71.png)

**Comment by wallace4BR** [comment]
My guess is if the user is somehow not cached
You can try setting the variable to `event-user` instead of `id of event-user` and see if it works

**Comment by SkyCraft78** [comment]
Hello  ! 
This Is not a real bug, it's simply how Discord works. 
Using `user with Id` it will search over every user the bot **has been cached**.
So if the desired user is not cached, it will return none. 
To force the cache of the user, even if its cached or not, use the `retrieve user` effect 😄
