### ISSUE TITLE
[REQUEST] on bot login event

### ISSUE THREAD

**Issue by vitusverden** [SkyCraft78/DiSky#8]
**Name:** `on bot login`

**Potential New Syntaxes:**
* Event: `on [new] [discord] bot login:`

**In-dept description of the new features:**
```
It would be nice to be able to do stuff when a bot logs in.
Event-values would include bot name (maybe token, I don't know if that would be used?) 
```
If #7 gets added, this is not needed.

**Comment by SkyCraft78** [comment]
This will be added in the next update.
Thanks 👍

**Comment by SkyCraft78** [comment]
Added in 534861d
